services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      args:
        NODE_ENV: development
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=finch-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-tax_finch_dev}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_SSL=${POSTGRES_SSL:-false}
      - DATABASE_POOL_MAX=${DATABASE_POOL_MAX:-10}
      - DATABASE_TIMEOUT=${DATABASE_TIMEOUT:-30000}
    depends_on:
      finch-postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    restart: unless-stopped
    networks:
      - tax-finch-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    stdin_open: true
    tty: true

  finch-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-tax_finch_dev}
      - POSTGRES_USER=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres-dev:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - tax-finch-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USERNAME:-postgres} -d ${POSTGRES_DATABASE:-tax_finch_dev}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local

networks:
  tax-finch-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
